Rework retry against Github API

diff --git a/docker/coinboot-download-helper b/docker/coinboot-download-helper
--- a/docker/coinboot-download-helper
+++ b/docker/coinboot-download-helper
@@ -1,5 +1,4 @@
 #!/bin/sh -e
-set -x
 
 # Copyright (C) 2018 Gunter Miegel coinboot.io
 #
@@ -30,12 +29,13 @@ BOOTDIR=/var/lib/tftpboot
 # If the value is 'latest' we determine the latest release, else we use the set value.
 
 if [ $RELEASE = latest ]; then
-  while [ -n "$TAG" ]; do
     RESPONSE=$($CURL --silent "https://api.github.com/repos/frzb/coinboot-debirf/tags")
-    echo "Github API is not returing an response, repeat ..."
     sleep 5
-    TAG=$(echo $RESPONSE | jq -r '.[0].name')
-  done
+    while ! TAG=$(echo $RESPONSE | jq -r '.[0].name'); do
+      echo "Calling the Github API has failed, repeat ..."
+      RESPONSE=$($CURL --silent "https://api.github.com/repos/frzb/coinboot-debirf/tags")
+      sleep 5
+    done
   echo "Using latest coinboot-debirf release: $TAG"
 fi
 URL=https://github.com/frzb/coinboot-debirf/releases/download/${TAG}
