Rework NIC handling or Vagrant, rework timeouts

diff --git a/server/run_coinboot b/server/run_coinboot
--- a/server/run_coinboot
+++ b/server/run_coinboot
@@ -1,7 +1,8 @@
 #!/bin/bash
 set -e -o pipefail
+set -x
 
-# Copyright (C) 2019 Gunter Miegel coinboot.io
+# Copyright (C) 2019-2020 Gunter Miegel coinboot.io
 #
 # This file is part of Coinboot.
 #
@@ -26,7 +27,7 @@ MACHINE_MAC_ADDRESS_UEFI='52:54:04:b9:ab:46'
 DEFAULT_ROUTE=$(ip route | grep default | grep -v br0)
 DEFAULT_GW=$(ip route | grep default | grep -v br0 | cut -d ' ' -f 3)
 EXT_IF=$(ip route show default | grep -oP '(?<=dev )\w+')
-TIMEOUT=240
+TIMEOUT=300
 
 echo "Debug environment at run_coinboot"
 env
@@ -55,8 +56,8 @@ get_bridge_interface() {
   ip a | grep '192.168.1.2/24' |grep -oP 'br-.*'
 }
 
-get_interface_for_bridge() {
-  ip a | grep '192.168.1.2/24' |grep -oP '\s(w+)$'
+export_interface_for_bridge() {
+  export COINBOOT_SERVER_IF=$(ip route |grep 192.168.1.0/24 | grep -oP '(?<=dev )\w+')
 }
 
 get_default_route() {
@@ -69,12 +70,8 @@ get_default_gateway() {
 
 update_default_route() {
   ip route
-  if [ ! -d "/vagrant" ]; then
-    sudo dhclient -v br0
-    ip route
-  else
-    echo "Not running at Travis CI - update of default route skipped"
-  fi
+  sudo dhclient -v br0
+  ip route
 }
 
 add_address_to_br0() {
@@ -86,7 +83,7 @@ move_ext_interface_to_bridge() {
   ip a
   if [[ -z  $(get_bridge_interface) ]] && ! ip a | grep -oP '\sbr0'; then
     sudo brctl addbr br0
-    sudo brctl addif br0 $EXT_IF
+    sudo brctl addif br0 $COINBOOT_SERVER_IF
     sudo ip link set br0 up
   fi
   brctl show
@@ -94,11 +91,11 @@ move_ext_interface_to_bridge() {
 
 migrate_ips_to_bridge_interface() {
   ip a
-  while ip -4 addr show dev $EXT_IF | grep inet; do
-   IP=$(ip -4 a show dev $EXT_IF | grep -m 1 inet | cut -d ' ' -f6)
+  while ip -4 addr show dev $COINBOOT_SERVER_IF | grep inet; do
+   IP=$(ip -4 a show dev $COINBOOT_SERVER_IF | grep -m 1 inet | cut -d ' ' -f6)
    echo "Migrating $IP to br0 now"
    sudo ip addr add $IP dev br0
-   sudo ip addr del $IP dev $EXT_IF
+   sudo ip addr del $IP dev $COINBOOT_SERVER_IF
   done
 }
 
@@ -124,7 +121,7 @@ wait_for_server_to_be_ready() {
 }
 
 run_with_libvirt_bios() {
-  sudo virt-install --pxe --name coinboot-bios --memory 1024 --disk none --network bridge=br0,mac=$MACHINE_MAC_ADDRESS_BIOS --boot menu=on,useserial=on --noautoconsole --graphics vnc,listen=0.0.0.0
+  sudo virt-install --pxe --name coinboot-bios --memory 1024 --vcpus 4 --disk none --network bridge=br0,mac=$MACHINE_MAC_ADDRESS_BIOS --boot menu=on,useserial=on --noautoconsole --graphics vnc,listen=0.0.0.0
 }
 
 run_with_libvirt_uefi() {
@@ -135,11 +132,20 @@ verify_and_shutdown_over_ssh() {
   local MACHINE_MAC_ADDRESS=$1
   local MACHINE_IP=$(get_ip_address_associated $MACHINE_MAC_ADDRESS)
 
-  echo 'Waiting for Coinboot machine to respond to our ICMP echo requests ...'
-  ping -w $TIMEOUT -c 1 $MACHINE_IP
+  local COUNTER=0
+  while ! ping -c1 $MACHINE_IP && [ $COUNTER < $TIMEOUT ]; do
+    sleep 1
+    ((COUNTERi++))
+    echo "Waiting $COUNTER second(s) Coinboot machine to respond to our ICMP echo requests ..."
+  done
 
-  echo 'Waiting for Coinboot machine to listen on port 22/SSH ...'
-  nc -w $TIMEOUT -z $MACHINE_IP 22
+  # Pure nc -z -w with timeout fails for ssh all the time, so again with the while loop.
+  local COUNTER=0
+  while ! nc -v -z $MACHINE_IP 22 && [ $COUNTER < $TIMEOUT ]; do
+    sleep 1
+    ((COUNTERi++))
+    echo "Waiting $COUNTER second(s) for Coinboot machine to listen on port 22/SSH ..."
+  done
 
   # FIXME: RELEASE does not expanse to date string when 'latest' is specified
   while ! sshpass -p ubuntu ssh -o StrictHostKeyChecking=no -l ubuntu -p 22 $MACHINE_IP "cat /etc/motd && lsb_release -a && uname -a && df -m && free -m && zramctl"; do
@@ -168,15 +174,26 @@ fi
 
 change_to_build_dir
 
+export_interface_for_bridge
+
 move_ext_interface_to_bridge
+
 migrate_ips_to_bridge_interface
-update_default_route
+
+#update_default_route
+
 echo 'nameserver 8.8.8.8' | sudo tee /etc/resolv.conf
+
 dig registry-1.docker.io || true
 
+# The Vagrant VMs has two network interfaces:
+# A default one for internet access and a second "private network" which we include in
+# as network bridge for the Coinboot Server Container and the Coinboot Qemu worker VMs.
+# Because of this we don't have to refresh the default route after moving IPs between interfaces.
+# TODO: Disable DHCP in default Vagrant network interface
 if ! [ -d "/vagrant" ]; then
-  add_address_to_br0
-  update_default_route
+ #add_address_to_br0
+ update_default_route
 fi
 
 # We also need to load the environment before calling docker-compose:
