Fix indentation

diff --git a/server/docker/coinboot-download-helper b/server/docker/coinboot-download-helper
--- a/server/docker/coinboot-download-helper
+++ b/server/docker/coinboot-download-helper
@@ -31,15 +31,15 @@ GITHUB_REPO=frzb/coinboot
 # we assign the RELEASE value to TAG.
 
 if [ $RELEASE = latest ]; then
+  RESPONSE=$($CURL --silent "https://api.github.com/repos/${GITHUB_REPO}/tags")
+  sleep 5
+  while ! TAG=$(echo $RESPONSE | jq -r '.[0].name'); do
+    echo "Calling the Github API has failed, repeat ..."
     RESPONSE=$($CURL --silent "https://api.github.com/repos/${GITHUB_REPO}/tags")
     sleep 5
-    while ! TAG=$(echo $RESPONSE | jq -r '.[0].name'); do
-      echo "Calling the Github API has failed, repeat ..."
-      RESPONSE=$($CURL --silent "https://api.github.com/repos/${GITHUB_REPO}/tags")
-      sleep 5
-    done
-  else
-    TAG=$RELEASE
+  done
+else
+  TAG=$RELEASE
 fi
 
 echo "Using latest coinboot-debirf release: $TAG"
