Fix git diff and switch to eoan (#17)
* Switch to apt-get download

* Work aroung linux-check-remove

* Fix globing pattern to collect correct initramfs

* linux-base is dependency of linux-image now

* Pass environment, work arround for slow boot by missing ttyS0

* Switch to eoan in Travic CI config as well

* Finalize with running depmod

* SSH port to 2022 to avoid conflict with vagrant

* Install kmod packakge providing depmod

* No subshell necessary in this case

* Change order of add/dell, update default route

* Order of functions, cleanup

* Debug ip setting before bridge creation

* Regex to not match virbr0

* Find out if name server is set wrong

* Give workspaces a try

* Add path to workspace

* Remove Gemfile

* Missing Rakefile, switch language to bash

* Force build to debug workspaces

* Add workspace to stage "build and run images"

* paths instead path .. plural damn

* Set job name from $KERNEL + $SUITE

* Set job name without environment variables

* Create workspaces for each SUITE and KERNEL

* DEBIRF_KERNEL instead SUITE alone

* Create symlinks to SUITE subdir

* Run install with -d - the directory mode

* Mixed up install -d with install -D

* Debug content of /mnt/debirf/build

* Correct path to build directory

* Remove chmod

* Detailed debugging of directory content

* Further debugging of symlinks

* Further debugging of symlinks

* Remove lost single quote

* Adjust symlinks to reflect not being inside container

* Cleanup after debugging

* Build  relative symlinks

* Add /mnt prefix to symlinks

* Add wildcard to workspace path

* Variables not working for workspaces - hardwire

* Remove create workspace stage

* First draft using github-release

* Ass missing syntax elements

* Use GITHUB_TOKEN set as secret variable at Travis CI

* Change order of global options

* Use find --exec for upload to Github Releases

* Remove extra 'do'

* Add tag to upload command

* Add file name flag to upload

* Add whitespace

* Use execdir

* Switch to Githubs hub for managing releasing

* Add sudo to apt

* Update before hand

* Install hub via Snap

* Add full path for using hub as Snap

* Add message

* Try github-release once more

* Debugging github-releases with set -x

* github-release not github-releases

* No leading ./ in results of find for nice labels

* New approach for find + xargs

* Correct path and name for find

* Switch to execdir

* Fix mixup between $1 and $1, add -l

* Switch to readlink -f to get fullpath

* Make it more sane: && instead of ;

* Debuf find | github-release

* Use only two arguments per command line

* Use intermediate prerelease for run_coinboot stage

* Debug docker-compose run

* Take care the we use RELEASE set from Travis CI

* Use TRAVIS_BUILD_ID

* Fix environment variable $TRAVIS_BUILD_ID

* Correct assignment of RELEASE

* Take care that RELEASE is handed in the container

* Fix indentation

* Build coinboot container image locally

* Add cleanup stage

* Don't ls /snap/bin

* github-release is installed for cleanup stage

* Debug git diff

* Proof if reports TRAVIS_COMMIT is empty on first branch push is true

* Debug diff with set -x

* Remove HEAD from git diff

* Building back debugging, Remove HEAD form TO_BUILD

* Fix damaged echo command

* Remove changes just placed for debugging

diff --git a/server/docker/coinboot-download-helper b/server/docker/coinboot-download-helper
--- a/server/docker/coinboot-download-helper
+++ b/server/docker/coinboot-download-helper
@@ -27,18 +27,22 @@ BOOTDIR=/var/lib/tftpboot
 GITHUB_REPO=frzb/coinboot 
 ## initramfs and kernel vmlinuz ##
 # RELEASE is set via an environment variable under ./conf/environment
-# If the value is 'latest' we determine the latest release, else we use the set value.
+# If the value is 'latest' we determine the latest release tag, else
+# we assign the RELEASE value to TAG.
 
 if [ $RELEASE = latest ]; then
+  RESPONSE=$($CURL --silent "https://api.github.com/repos/${GITHUB_REPO}/tags")
+  sleep 5
+  while ! TAG=$(echo $RESPONSE | jq -r '.[0].name'); do
+    echo "Calling the Github API has failed, repeat ..."
     RESPONSE=$($CURL --silent "https://api.github.com/repos/${GITHUB_REPO}/tags")
     sleep 5
-    while ! TAG=$(echo $RESPONSE | jq -r '.[0].name'); do
-      echo "Calling the Github API has failed, repeat ..."
-      RESPONSE=$($CURL --silent "https://api.github.com/repos/${GITHUB_REPO}/tags")
-      sleep 5
-    done
-  echo "Using latest coinboot-debirf release: $TAG"
+  done
+else
+  TAG=$RELEASE
 fi
+
+echo "Using latest coinboot-debirf release: $TAG"
 
 DOWNLOAD_URL=https://github.com/${GITHUB_REPO}/releases/download/${TAG}
 
