Fixed regex to install zstd_compress.ko, bump zstd version

diff --git a/debirf/debirf b/debirf/debirf
--- a/debirf/debirf
+++ b/debirf/debirf
@@ -196,21 +196,23 @@ create_initrd_plugin() {
     cp -f /lib/klibc-* "$NEST_ROOT"/lib/
 
     # Upstream ZSTD
-    wget https://github.com/facebook/zstd/releases/download/v1.5.1/zstd-1.5.1.tar.gz -P /tmp
-    echo "e28b2f2ed5710ea0d3a1ecac3f6a947a016b972b9dd30242369010e5f53d7002 /tmp/zstd-1.5.1.tar.gz" | sha256sum --check
-    tar -xvzf /tmp/zstd-1.5.1.tar.gz -C $DEBIRF_ROOT/tmp
+    wget https://github.com/facebook/zstd/releases/download/v1.5.2/zstd-1.5.2.tar.gz -P /tmp
+    echo "7c42d56fac126929a6a85dbc73ff1db2411d04f104fae9bdea51305663a83fd0 /tmp/zstd-1.5.2.tar.gz" | sha256sum --check
+    tar -xvzf /tmp/zstd-1.5.2.tar.gz -C $DEBIRF_ROOT/tmp
     debirf_exec apt update
     debirf_exec apt install --yes build-essential
-    debirf_exec make -C /tmp/zstd-1.5.1/programs/ zstd-decompress
-    install -vD "$DEBIRF_ROOT/tmp/zstd-1.5.1/programs/zstd-decompress" "$NEST_ROOT"/"bin"
+    debirf_exec make -C /tmp/zstd-1.5.2/programs/ zstd-decompress
+    install -vD "$DEBIRF_ROOT/tmp/zstd-1.5.2/programs/zstd-decompress" "$NEST_ROOT"/"bin"
     rm -rf $DEBIRF_ROOT/tmp/zstd*
     debirf_exec apt purge --yes ^gcc-9 build-essential
     debirf_exec apt autoremove --yes
     debirf_exec apt autoclean
 
-
+    ldd "$NEST_ROOT"/bin/zstd-decompress
+    # To run zstd-decompress at the first init stage we need to
+    # copy the libaries linked by zstd-compress to the nested initramfs
     for libary in $(ldd "$NEST_ROOT"/bin/zstd-decompress | grep -oP '/lib.*\s+'); do
-        install -vD "$DEBIRF_ROOT"/"$libary" "$NEST_ROOT"/"$libary"
+        install -vD "$DEBIRF_ROOT""$libary" "$NEST_ROOT""$libary"
     done
 
     # Copy in the modules for ZRAM and for Zstandard
@@ -233,21 +235,24 @@ create_initrd_plugin() {
     install -vD "$DEBIRF_ROOT/$ZSTD_MODULE" "$NEST_ROOT"/"$ZSTD_MODULE"
 
     # Kernels above 5.4 have zstd compression in the kernel
-    if [[ $DEBIRF_KERNEL =~ '5.4' ]]; then 
-    local ZSTD_COMPRESS_MODULE=/lib/modules/${KERNEL_VERS}/kernel/lib/zstd/zstd_compress.ko
-    install -vD "$DEBIRF_ROOT/$ZSTD_COMPRESS_MODULE" "$NEST_ROOT"/"$ZSTD_COMPRESS_MODULE"
+    if [[ $DEBIRF_KERNEL =~ 5\.([4-9]|[1-9][0-9]) ]]; then
+        local ZSTD_COMPRESS_MODULE=/lib/modules/${KERNEL_VERS}/kernel/lib/zstd/zstd_compress.ko
+        install -vD "$DEBIRF_ROOT"/"$ZSTD_COMPRESS_MODULE" "$NEST_ROOT"/"$ZSTD_COMPRESS_MODULE"
+    else
+        echo "Abort: No support for ZSTD in kernel $DEBIRF_KERNEL."
+        exit 1
     fi
 
-    # symlink /lib64 if that is done on host
-    # FIXME: is this necessary?
+    # Symlink /lib64 if that is done on host
     if [ -L /lib64 ] && [ $(readlink /lib64) = /lib ] ; then
-	ln -s /lib "$NEST_ROOT"/lib64
+        ln -s /lib "$NEST_ROOT"/lib64
     fi
 
 # There are two constraints for running init.
 # We need python3 to merge the DPKG status file.
 # To extract the plugin archives in place
-# we need / to be run as tmpfs and not as rootfs with only öimited capacity.
+# we need / to be run as final tmpfs and not as
+# intial rootfs with only limited capacity.
 #
 # Caused by this We have to run init twice but with separate scripts.
 # 1. Minimal busybox based environment to extract
